### ISSUE TITLE
Existing command 'TEST_RESONANCES' not found in gcode_macro rename

### ISSUE THREAD

**Issue by kurtblah** [Frix-x/klippain#153]
Existing command 'TEST_RESONANCES' not found in gcode_macro rename (klipper error)

I get this when I have the accelerometer disabled in printer.cfg AND with the two new resonance testing variables commented out in variables.cfg.

No error while accel is enabled.

**Comment by Frix-x** [comment]
Hello,

Thanks for raising this issue. It's indeed a bug as the `TEST_RESONNANCES` override should not be included if not using an accelerometer. I think it's due to this line that always match the file even if it should'nt: https://github.com/Frix-x/klippain/blob/5fe6459bf3e90ca20e191f6d7a3e6ed86af14a35/config/machine.cfg#L47

I'll add a bugfix in the next release!
