### ISSUE TITLE
relative_reference_index will break Z auto Calibration addon.

### ISSUE THREAD

**Issue by yanfoo** [Frix-x/klippain#247]
Hello, I updated Klipper to the latest, shame on me.

The change in Klipper recent update did require some changes.

relative_reference_index: 40 removal into the following at some point in time.
xxx, yyy are the center of my bed in my case 175, 175.

[bed_mesh]
zero_reference_position: xxx, yyy

For the z auto calibration see here if you already updated Klipper:
https://github.com/protoloft/klipper_z_calibration/issues/104
Get the zip posted by todstelzer or wait until it makes it way thru the pull request.
then add
[z_calibration]
bed_xy_position: xxx, yyy

I have printed mostly full beds lately so I am unsure if the bed mesh macro was affected or not by this but it works for full meshes.

**Comment by VORONENTHUSIAST** [comment]
Not sure if I'm missunderstanding you here, Frix-x, but relative_reference_index no longer works, and Klipper instructs you to change it due to being depreciated in the latest update. 

relative bed mesh macro that I'm using still works, after changing the bed_mesh to include zero_reference_position: xxx, yyy
