### ISSUE TITLE
Probe servo is very hot

### ISSUE THREAD

**Issue by Glenn-Kerselaers** [Frix-x/klippain#257]
I've got a Voron Switchwire with a KlickyProbe servo dock. Everything works okay using Klippain. However, I have noticed that the servo, used to deploy/retract the probe dock, feels very hot (my IR thermometer is broken so can't measure accurately). I have compared the temperature when using Klippain and KlickyProbe macro's. When using the KlickyProbe macro's the servo doesn't get hot.
It looks like Klippain keeps driving the servo although it's already retracted and held by magnets.

**Comment by Frix-x** [comment]
Hello,

Yes you're right, it's something that I also discovered. I just checked and I think it's because I was missing the WIDTH=0 call after moving the servo.
So now everything should be fixed in the develop branch (to be publicly released soon) by this commit: a898f1368a22fcc362d3d5f8415bca113c83837e
