### ISSUE TITLE
Invalid pin alias 'EBBCan: PD0'

### ISSUE THREAD

**Issue by johnrcrc** [Frix-x/klippain#429]
### Klippain branch

- [X] I confirm using the main branch

### Version

v0.12.0-61-gb50d6669

### Describe the bug and expected behavior

Hello,

After klippain instalation thiw message apeared: Invalid pin alias 'EBBCan: PD0' and i don't know what i have to change.
My printer is voron 2.4 with pi and two skrs 1.3 u2c module and sb2240 canbus

### Additional information and klippy.log

[1704584972128.zip](https://github.com/Frix-x/klippain/files/13853213/1704584972128.zip)

**Comment by Frix-x** [comment]
Hello,

This is normal since you used EBBcan:PIN in the aliases and this is not possible.
The EBB is the [mcu toolhead] and is the one that needs to be used in the overrides to map the Klippain pins to it. On the main mcu, you don't want to use anything else than PIN=Pxx.x without any symbol or anything else.

Please see [this documentation](https://github.com/Frix-x/klippain/blob/main/docs/pinout.md) to understand how the pinouts are working and [this one](https://github.com/Frix-x/klippain/blob/main/docs/overrides.md) to creates the overrides to remap to the correct pins (ie. klipper_pin: toolhead:PROBE_INPUT for example).
